### ISSUE TITLE
请问这里提供的数据和safetyBench中用于测试的数据是同一份吗？

### ISSUE THREAD

**Issue by WinncyNing** [thu-coai/Safety-Prompts#14]
首先非常感谢您所做的贡献！我当下需要一些安全性语料用于训练/微调大模型来获得更好的安全性表现并进行测试评价，我有一些不清楚的是在这个项目中所用的数据和在safetyBench中所用的数据是否一样？也就是说是否可以用这个项目下的数据进行训练，之后再用那个平台的数据进行测试？

**Comment by TissueC** [comment]
数据不一样
