### ISSUE TITLE
Why test leaderboard only have half of the models of dev leaderboard?

### ISSUE THREAD

**Issue by zhimin-z** [thu-coai/Safety-Prompts#15]
![image](https://github.com/thu-coai/Safety-Prompts/assets/8592144/be7e5461-d9e9-43e3-844c-f0d9df5edc05)

**Comment by TissueC** [comment]
隐藏测试集数据量比较大，我们仅测试了这些模型。

**Comment by zhimin-z** [comment]
我能问下公开数据集更隐藏数据集的比例吗？
