### ISSUE TITLE
请问访问评测平台一定要清华内网吗？

### ISSUE THREAD

**Issue by Ligandlly** [thu-coai/Safety-Prompts#18]
点击[中文大模型安全评测平台](http://coai.cs.tsinghua.edu.cn/leaderboard/)的界面如下：
<img width="1158" alt="Screenshot 2023-12-08 at 15 13 03" src="https://github.com/thu-coai/Safety-Prompts/assets/42318879/c88cf572-c7d3-4f9f-9d8e-54e9684ebc28">

**Comment by zhimin-z** [comment]
Any update?

**Comment by TissueC** [comment]
我们正在解决这个问题

**Comment by zhimin-z** [comment]
> 我们正在解决这个问题

It gets fixed! I think we can close it.
