### ISSUE TITLE
Is there any downloadable evaluation table shown in the leaderboards?

### ISSUE THREAD

**Issue by zhimin-z** [thu-coai/Safety-Prompts#19]
I want to find out csv format of the leaderboard tables.

**Comment by TissueC** [comment]
请在网站主页点击 “ 提交 ” 按钮，并按照提示进行操作。

**Comment by zhimin-z** [comment]
> 请在网站主页点击 “ 提交 ” 按钮，并按照提示进行操作。

我看你误解了我的问题，我是说榜单里的结果怎么下载成csv表格（捂脸）

**Comment by TissueC** [comment]
目前没有办法下载成csv
