### ISSUE TITLE
What model is the LLM used in Figure 3？

### ISSUE THREAD

**Issue by XiaoluJiayou** [thu-coai/Safety-Prompts#20]
hello, What model is the LLM used in Figure 3 of the paper to determine whether the conversation is safe, and does it require retraining or fine-tuning?
![image](https://github.com/thu-coai/Safety-Prompts/assets/94163973/c67b89f9-cadf-4bbe-b8d3-a5d723a6c692)

**Comment by TissueC** [comment]
在当时使用的是InstructGPT，但放到今天来看这个选择显然不是最优了。
