### ISSUE TITLE
数据集的回复部分有用专门的安全相关prompt吗？

### ISSUE THREAD

**Issue by IcyFeather233** [thu-coai/Safety-Prompts#21]
注意到你们的论文中主要是讲述的问题的构造，在README中看到回复来自于ChatGPT (GPT-3.5-turbo)，这个是直接把问题输入给回复来自于ChatGPT (GPT-3.5-turbo)来获取答案吗？还是构造了专门用于安全防护的prompt呢？

**Comment by TissueC** [comment]
直接把问题输入给GPT的
