### ISSUE TITLE
手工标注的prompt

### ISSUE THREAD

**Issue by zhuang-li** [thu-coai/Safety-Prompts#3]
你好，感谢您的工作，我想请问数据中哪些是人工标注的，哪些是通过GPT增广的？数据集中是否有说明呢？

**Comment by TissueC** [comment]
该份数据集（SafetyPrompts）都是GPT增广的。人工编写的我们开放了公开测试集（约2k条），请在我们的leaderboard网站中注册并下载（http://coai.cs.tsinghua.edu.cn/leaderboard/）。

**Comment by zhuang-li** [comment]
> 该份数据集（SafetyPrompts）都是GPT增广的。人工编写的我们开放了公开测试集（约2k条），请在我们的leaderboard网站中注册并下载（[http://coai.cs.tsinghua.edu.cn/leaderboard/）。](http://coai.cs.tsinghua.edu.cn/leaderboard/%EF%BC%89%E3%80%82)

好的，谢谢，我注册了，但是需要审核？请问多久能通过?
