### ISSUE TITLE
在平台上提交了公开数据集的评测结果，但是一直没出结果。

### ISSUE THREAD

**Issue by fengyh3** [thu-coai/Safety-Prompts#8]
如题，联系了邮箱也没有回复～所以想问问目前是什么状态呢？

**Comment by TissueC** [comment]
抱歉。该平台第一版基准因为评测的是生成数据的结果，每次评测都消耗时间和精力巨大。我们意识到了这个问题，我们正在修改评测基准的方式，之后会有以评判选择题的方式的评测基准。
